#!/bin/bash

#
# Description:
#   LIG is a Live Images Generator.
#  
#   This program generate a chroot system from a debian repository in order
#   to create a squashfs compressed image of that system for being able to run
#   as a live GNU/Linux system.
#
# Authors: 
#   Juan Jesús Ojeda Croissier (juanje) <jojeda@emergya.es>   
#
# Last modified: 
#   $Date: 2007-05-21 18:45:56 +0200 (lun, 21 may 2007) $ 
#   $Author: jojeda $
#   $Rev: 467 $
#


# load functions from library
. $(dirname $0)/functions

## Start main program ##

#must_be_root

# load the config
load_config

# parse the menu options
menu "$@"

# if clean is selected, just clean up and exit
if [ "$clean" = "yes" ]; then
    clean
fi

if [ "$update" = "yes" ]; then
    update_chroot
else
    install_image
fi

bye

# vim:ai:et:sts=4:tw=80:sw=4:
