#!/bin/sh

if test "$1" = "upgrade" -o "$1" = "install"; then 
  if test -d /usr/lib/firefox/extensions/guadafox@guadalinex.org; then
    rm -rf /usr/lib/firefox/extensions/guadafox@guadalinex.org
  fi

  if test -d /usr/lib/firefox-addons/extensions/guadafox@guadalinex.org; then
    rm -rf /usr/lib/firefox-addons/extensions/guadafox@guadalinex.org
  fi
fi

if [ install = "$1"  ]; then
    dpkg-divert --package guadafox --add --rename \
             --divert /etc/firefox-3.0/profile/bookmarks.html.real /etc/firefox-3.0/profile/bookmarks.html
    ln -s /usr/share/guadafox/bookmarks/bookmarks.html /etc/firefox-3.0/profile/bookmarks.html
fi

