#!/bin/bash

# remove diversion of /etc/lsb-release
rm -f /etc/lsb-release
dpkg-divert --package guadalinex-minima-meta --rename --quiet --remove /etc/lsb-release

# remove diversion of /etc/issue
rm -f /etc/issue
dpkg-divert --package guadalinex-minima-meta --rename --quiet --remove /etc/issue

# remove diversion of /etc/issue.net
rm -f /etc/issue.net
dpkg-divert --package guadalinex-minima-meta --rename --quiet --remove /etc/issue.net
