#!/bin/sh

if [ install = "$1"  ]; then
    dpkg-divert --package guada-ubiquity --add --rename \
             --divert /usr/lib/ubiquity/ubiquity/frontend/__init__.py.real /usr/lib/ubiquity/ubiquity/frontend/__init__.py
    ln -s /usr/lib/guada-ubiquity/ubiquity/frontend/__init__.py /usr/lib/ubiquity/ubiquity/frontend/__init__.py
    
    dpkg-divert --package guada-ubiquity --add --rename \
             --divert /usr/share/ubiquity/ubiquity-gtkui.desktop.real /usr/share/applications/ubiquity-gtkui.desktop
    ln -s /usr/share/guada-ubiquity/ubiquity-guadaui.desktop /usr/share/applications/ubiquity-gtkui.desktop
fi

