#!/bin/bash
#
# boot-hppa
#
# $1 is the CD number
# $2 is the temporary CD build dir

# palo is used to make ISOs bootable on HPPA.

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDROOT=$2
if [ "$DI_WWW_HOME" = "default" ];then
   DI_WWW_HOME="http://people.debian.org/~jbailey/d-i/hppa/daily/cdrom/2.6"
fi
if [ ! "$DI_DIST" ]; then
   DI_DIST="$DI_CODENAME"
fi
if [ -z "$DI_PATH" ]; then
   DI_PATH="$($BASEDIR/tools/find-newest-installer)"
fi

case $PROJECT in
    edubuntu)
	DEFAULT_PRESEED='preseed/file=/cdrom/preseed/edubuntu.seed'
	;;
    kubuntu)
	DEFAULT_PRESEED='preseed/file=/cdrom/preseed/kubuntu.seed'
	;;
    ubuntu-server)
	DEFAULT_PRESEED='preseed/file=/cdrom/preseed/ubuntu-server.seed'
	;;
    *)
	DEFAULT_PRESEED=
	;;
esac

:> $1.mkisofs_opts

"$BASEDIR/tools/sorting_weights" "$N"
echo -n "-sort $(pwd)/$N.weights " >> $N.mkisofs_opts

# Only disk 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then
	exit 0
fi

PALODEB="$($BASEDIR/tools/apt-selection cache show palo | \
	sed -n 's/^Filename: \(.*_hppa.deb\)$/\1/p')"
ar p "${MIRROR}/${PALODEB}" data.tar.gz | tar xz ./usr/share/palo/iplboot
mv usr/share/palo/iplboot $CDROOT/install/iplboot

if [ ! "$DI_WWW_HOME" ];then
	DI_DIR="$DI_PATH/current/images/cdrom/2.6"
else
	DI_DIR="di_stuff"
	mkdir "$DI_DIR"
	wget -r -nd --no-parent -P "$DI_DIR" "$DI_WWW_HOME"
fi
	
cp "$DI_DIR"/vmlinux-*-hppa32 "$CDROOT/install"
cp "$DI_DIR"/vmlinux-*-hppa64 "$CDROOT/install"
cp "$DI_DIR"/initrd.gz "$CDROOT/install"

install_languages "$CDROOT"

if [ "$CDIMAGE_LIVE" = 1 ]; then
    # This should really be:
    #EXTRA_ARGS='casper/enable=true casper-udeb/snapshot/backing-file=/cdrom/casper/filesystem.cloop'
    # ... but this overflows palo's command-line limit.
    EXTRA_ARGS='casper/enable=true'
else
    EXTRA_ARGS=
fi

echo " -hppa-cmdline 0/vmlinux,${DEFAULT_PRESEED:+$DEFAULT_PRESEED,}${EXTRA_ARGS:+$EXTRA_ARGS,}root=/dev/ram,initrd=0/ramdisk,ramdisk_size=1048576" >> $1.mkisofs_opts
K32=$(ls $CDROOT/install/vmlinux-*-hppa32 | sed 's?^.*/install/?install/?g')
echo " -hppa-kernel-32 $K32" >> $1.mkisofs_opts
K64=$(ls $CDROOT/install/vmlinux-*-hppa64 | sed 's?^.*/install/?install/?g')
echo " -hppa-kernel-64 $K64" >> $1.mkisofs_opts
echo " -hppa-bootloader install/iplboot" >> $1.mkisofs_opts
echo " -hppa-ramdisk install/initrd.gz" >> $1.mkisofs_opts

exit 0
