assert.o: assert.c
britney-py.o: britney-py.c dpkg.h templates.h memory.h
checklib.o: checklib.c dpkg.h templates.h memory.h
dpkg.o: dpkg.c dpkg.h templates.h memory.h
freelist.o: freelist.c templates.h memory.h
memory.o: memory.c memory.h templates.h freelist.h
memory2.o: memory2.c
