#!/bin/sh

set -e

self="$(basename "$0")"

action="$1"

case "$action" in
  remove)
    [ -x /usr/sbin/update-gconf-defaults ] && update-gconf-defaults
  ;;
  purge)
    # FIXME I am probably a very old cleanup snippet, check whether you can
    # remove me!
    rm -rf /var/lib/gnome
  ;;
  upgrade|failed-upgrade|abort-install|abort-install|abort-upgrade|disappear)
  ;;
  *)
    echo "$self: W: unknown action \`$action'" >&2
  ;;
esac

#DEBHELPER#
