#!/bin/sh -e
#Provides all mythbuntu questions asked by
#ubiquity during install process
# Written by Mario Limonciello <superm1@ubuntu.com>
# Copyright (C) 2007 Mario Limonciello
# Copyright (C) 2007 Jared Greenwald

. /usr/share/debconf/confmodule

#determine themes
db_input high mythbuntu/officialthemes || true
db_input high mythbuntu/communitythemes || true
