.TH "GNOME-VOLUME-MANAGER" "1" "9 April 2004"
.SH NAME
gnome-volume-properties \- configure the gnome-volume-manager daemon.

.SH SYNOPSIS
.B gnome-volume-properties  

.SH DESCRIPTION
gnome-volume-manager is a GNOME daemon that acts as a policy agent in
top of the kernel, udev, d-bus and HAL. It listens to HAL events and
reacts with user-configurable actions. Currently it supports automount
of new media and hot-plugged devices, autorun, autoplay for Cd's and
DVDs, and automatic camera management. It is expected to be simple and
free of polling and other evil hacks.

.B gnome-volume-properties 
allows you to configure gnome-volume-manager.

.SH OPTIONS
This program accepts all the standard GNOME and GTK+ options, which
follow  the  usual  GNU command line syntax, with long options starting
with two dashes (`-').

.SH SEE ALSO
.BR gnome-volume-manager (1)

.SH AUTHOR
gnome-volume-manager was written by Robert Love <rml@ximian.com>.

This manual page was written by Sjoerd Simons <sjoerd@debian.org> for the
Debian system (but may be used by others).
