Document: suppletorydiskgenerator
Title: Debian suppletorydiskgenerator Manual
Author: <insert document author here>
Abstract: This manual describes what suppletorydiskgenerator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/suppletorydiskgenerator/suppletorydiskgenerator.sgml.gz

Format: postscript
Files: /usr/share/doc/suppletorydiskgenerator/suppletorydiskgenerator.ps.gz

Format: text
Files: /usr/share/doc/suppletorydiskgenerator/suppletorydiskgenerator.text.gz

Format: HTML
Index: /usr/share/doc/suppletorydiskgenerator/html/index.html
Files: /usr/share/doc/suppletorydiskgenerator/html/*.html

  
