#!/bin/bash

MENU_LST="/boot/grub/menu.lst"

# removing menu.lst property
[ $MENU_LST != "$(dpkg-divert --truename $MENU_LST)" ] && rm -f $MENU_LST && dpkg-divert --rename --remove $MENU_LST

# menu.lst gv5 ownage
dpkg-divert --package guadalinex-artwork --rename --quiet --add $MENU_LST

# generating a clean menu.lst skel (splash.xpm.gz recognition)
update-grub -y

# generate a new menu.lst from current (using it as skel)
sed -e 's/### BEGIN AUTOMAGIC KERNELS LIST/# Guadalinex Grub theme config\n\nforeground ffffff\nbackground 004174\nviewport 1 0 80 30\nshadow 0\n\n### BEGIN AUTOMAGIC KERNELS LIST/g' /boot/grub/menu.lst > /boot/grub/menu.lst.gv5

# link the diverted file
cd /boot/grub
test -f $MENU_LST && rm $MENU_LST
ln -fs menu.lst.gv5 $MENU_LST
cd -
