#!/bin/sh

if [ remove = "$1" ]; then
    rm -f /usr/lib/ubiquity/ubiquity/frontend/__init__.py 
    dpkg-divert --package guada-ubiquity --remove --rename \
             --divert /usr/lib/ubiquity/ubiquity/frontend/__init__.py.real /usr/lib/ubiquity/ubiquity/frontend/__init__.py
fi



