#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
# Authors : Roberto Majadas <roberto.majadas@openshine.com>
#           Oier Blasco <oierblasco@gmail.com>
#           Alvaro Peña <alvaro.pena@openshine.com>
#
# Copyright (c) 2003-2007, Telefonica Móviles España S.A.U.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.

# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.

# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
import gobject
import PPPManager
import sys
from optparse import OptionParser
import os
import syslog

def write_pid_file(pid_file):
    syslog.syslog(syslog.LOG_INFO,"Creando fichero pid %s" % pid_file)
    if pid_file is None :
        return
    try:
        dirname = os.path.dirname(pid_file)
        if not os.path.exists(dirname):
            os.makedirs(dirname)
        pid = os.getpid()
        fd = open(pid_file,"w")
        fd.write("%s" % pid)
        fd.close()
        syslog.syslog(syslog.LOG_INFO,"CreandO fichero pid %s con exito" % pid_file)
    except Exception ,msg:
        syslog.syslog(syslog.LOG_INFO,"PPPHeper failed %s" % msg)
        sys.exit(1)



def main():
        
    syslog.openlog("PPPHelper")
    parser = OptionParser()
    parser.add_option("-p", "--pid-file", dest="pid_file", help="pid File", metavar="PID_FILE")
    parser.add_option("--no-daemon",action="store_false", dest="daemon", default=True, help="No se crea un demonio")
    (options, args) = parser.parse_args()

    syslog.syslog(syslog.LOG_INFO,"Creando demonio")
    ret =0 
    if options.daemon:
        ret = PPPManager.create_daemon()
    else:
        print "No nos hacemos demonio"
    write_pid_file(options.pid_file)
    syslog.syslog(syslog.LOG_INFO,"Creando objecto debus")
    manager = PPPManager.get_manager()
    syslog.syslog(syslog.LOG_INFO,"ejecutando ruunloop")
    gobject.MainLoop().run()
    syslog.syslog(syslog.LOG_INFO,"Nos vamos")
    sys.exit(ret)
if __name__ == "__main__":
    try:
        main()
    except Exception,msg:
        syslog.syslog(syslog.LOG_INFO,"PPPHeper failed %s" % msg)
        sys.exit(1)
