Document: lemurae
Title: Debian lemurae Manual
Author: <insert document author here>
Abstract: This manual describes what lemurae is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lemurae/lemurae.sgml.gz

Format: postscript
Files: /usr/share/doc/lemurae/lemurae.ps.gz

Format: text
Files: /usr/share/doc/lemurae/lemurae.text.gz

Format: HTML
Index: /usr/share/doc/lemurae/html/index.html
Files: /usr/share/doc/lemurae/html/*.html

  
