#!/bin/sh -e
#Provides all mythbuntu questions asked by
#ubiquity during install process
# Written by Mario Limonciello <superm1@ubuntu.com>
# Copyright (C) 2007 Mario Limonciello
# Copyright (C) 2007 Jared Greenwald

. /usr/share/debconf/confmodule


#determine mysql info
db_input high mythtv/mysql_mythtv_user || true
db_input high mythtv/mysql_mythtv_password || true
db_input high mythtv/mysql_mythtv_dbname || true
db_input high mythtv/mysql_host || true
#root password
db_input high mythtv/mysql_admin_password || true
#mythweb htaccess
db_input high mythweb/enable || true
db_input high mythweb/username || true
db_input high mythweb/password || true
