Welcome to Ubuntu ${DEBIAN_VERSION} (${CODENAME})!

This is an Ubuntu installation ${MEDIA_TYPE},
built on ${BUILD_DATE}.

The default option is 'install'. For maximum
control, you can use the 'expert' option.

To use a different video mode, use 'install video=ps3fb:mode:X',
setting X to the video mode (such as 3 for 720p). See
https://help.ubuntu.com/community/PlayStation_3#video for a table of
modes.

If in doubt, just press Enter.

