Document: gedit-plugin-tloleo
Title: Debian gedit-plugin-tloleo Manual
Author: <insert document author here>
Abstract: This manual describes what gedit-plugin-tloleo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gedit-plugin-tloleo/gedit-plugin-tloleo.sgml.gz

Format: postscript
Files: /usr/share/doc/gedit-plugin-tloleo/gedit-plugin-tloleo.ps.gz

Format: text
Files: /usr/share/doc/gedit-plugin-tloleo/gedit-plugin-tloleo.text.gz

Format: HTML
Index: /usr/share/doc/gedit-plugin-tloleo/html/index.html
Files: /usr/share/doc/gedit-plugin-tloleo/html/*.html

  
