#!/bin/bash

# backup old sources.list

cp /etc/apt/sources.list /etc/apt/sources.list.addon


MOUNTPOINT=$(mount |grep iso9660|awk '{print $3}')
LABEL=$(volname|grep GSD)

if [ ! -z "$LABEL" ];then
    gnome-app-install.distrib --addon-cd=$MOUNTPOINT
else
    zenity --error --text "No hay ningún disco de suplementos en la unidad"
fi

# restore old sources.list

cp /etc/apt/sources.list.addon /etc/apt/sources.list
