#!/bin/bash -x

# guadalinex "supplement" generator

BDIR=$TDIR/$CODENAME-$FULLARCH

rm -fr $BDIR/CD1/pool/*
rm -fr $BDIR/CD1/dist/*

if [ "$SUPPLEMENT" != "" ]; then
        cp -a $CDIMAGE_ROOT/supplement/master/pool/* $BDIR/CD1/pool/
        cp -a $CDIMAGE_ROOT/supplement/master/dists/* $BDIR/CD1/dists/
        cp -a $CDIMAGE_ROOT/supplement/master/guadalinex-suplementos-apps $BDIR/CD1/
        cp -a $CDIMAGE_ROOT/supplement/master/README.diskdefines $BDIR/CD1/
fi
