#! /bin/sh

PREREQ=""
DESCRIPTION="Regenerating SSL Certificate..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

rm -f /root/etc/ssl/private/ssl-cert-snakeoil.key
chroot /root /usr/sbin/make-ssl-cert generate-default-snakeoil

log_end_msg
