'\" t
.TH man 1 "14 Febrero de 2006" "1.0" "Pagina man de extras-installer"
.SH NAME
Ri_li \- Script para instalacion de software no libre en Guadalinex v4.
.SH SYNOPSIS
.\" Syntax goes here. 
.B extras-installer
.SH DESCRIPTION
.B extras-installer
es un script con zenity para la instalacion de software no libre no incluido en el CD live de Guadalinex v5. 
.SH OPTIONS
extras-installer no admite opciones de linea de comandos.
.SH FILES
.P
.I /usr/bin/extras-installer
.P
.I /usr/share/applications/extras-installer.desktop
.SH AUTHOR
.nf
Pagina man escrita por Junta de Andalucia <packmaster@guadalinex.org>
.fi

